/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ClientStatus = IDL.Variant({
  'Inactive' : IDL.Null,
  'Prospect' : IDL.Null,
  'Active' : IDL.Null,
});
export const CreateClientPayload = IDL.Record({
  'status' : ClientStatus,
  'company_name' : IDL.Text,
  'email' : IDL.Text,
  'contact_name' : IDL.Text,
  'phone' : IDL.Text,
});
export const ClientId = IDL.Nat;
export const Timestamp = IDL.Int;
export const ClientPublic = IDL.Record({
  'id' : ClientId,
  'status' : ClientStatus,
  'company_name' : IDL.Text,
  'created_at' : Timestamp,
  'email' : IDL.Text,
  'contact_name' : IDL.Text,
  'phone' : IDL.Text,
});
export const JobType = IDL.Variant({
  'Contract' : IDL.Null,
  'PartTime' : IDL.Null,
  'FullTime' : IDL.Null,
});
export const CreateJobPostingPayload = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'is_active' : IDL.Bool,
  'department' : IDL.Text,
  'requirements' : IDL.Text,
  'location' : IDL.Text,
  'job_type' : JobType,
});
export const JobPostingId = IDL.Nat;
export const JobPostingPublic = IDL.Record({
  'id' : JobPostingId,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'created_at' : Timestamp,
  'is_active' : IDL.Bool,
  'department' : IDL.Text,
  'requirements' : IDL.Text,
  'location' : IDL.Text,
  'job_type' : JobType,
});
export const LeadStatus = IDL.Variant({
  'New' : IDL.Null,
  'Closed' : IDL.Null,
  'Contacted' : IDL.Null,
  'Qualified' : IDL.Null,
});
export const CreateLeadPayload = IDL.Record({
  'status' : LeadStatus,
  'source' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'company' : IDL.Text,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
});
export const LeadId = IDL.Nat;
export const LeadPublic = IDL.Record({
  'id' : LeadId,
  'status' : LeadStatus,
  'updated_at' : Timestamp,
  'source' : IDL.Text,
  'name' : IDL.Text,
  'created_at' : Timestamp,
  'email' : IDL.Text,
  'company' : IDL.Text,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
});
export const ProjectStatus = IDL.Variant({
  'OnHold' : IDL.Null,
  'Planning' : IDL.Null,
  'InProgress' : IDL.Null,
  'Completed' : IDL.Null,
});
export const UserId = IDL.Principal;
export const CreateProjectPayload = IDL.Record({
  'status' : ProjectStatus,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'end_date' : IDL.Text,
  'start_date' : IDL.Text,
  'progress' : IDL.Nat,
  'client_id' : ClientId,
  'budget' : IDL.Nat,
  'owner_principal' : UserId,
});
export const ProjectId = IDL.Nat;
export const ProjectPublic = IDL.Record({
  'id' : ProjectId,
  'status' : ProjectStatus,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'end_date' : IDL.Text,
  'created_at' : Timestamp,
  'start_date' : IDL.Text,
  'progress' : IDL.Nat,
  'client_id' : ClientId,
  'budget' : IDL.Nat,
  'owner_principal' : UserId,
});
export const TaskStatus = IDL.Variant({
  'Done' : IDL.Null,
  'ToDo' : IDL.Null,
  'InProgress' : IDL.Null,
});
export const TaskPriority = IDL.Variant({
  'Low' : IDL.Null,
  'High' : IDL.Null,
  'Medium' : IDL.Null,
});
export const CreateTaskPayload = IDL.Record({
  'status' : TaskStatus,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'assigned_to' : UserId,
  'due_date' : IDL.Text,
  'priority' : TaskPriority,
  'project_id' : ProjectId,
});
export const TaskId = IDL.Nat;
export const TaskPublic = IDL.Record({
  'id' : TaskId,
  'status' : TaskStatus,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'created_at' : Timestamp,
  'assigned_to' : UserId,
  'due_date' : IDL.Text,
  'priority' : TaskPriority,
  'project_id' : ProjectId,
});
export const ContactSubmissionId = IDL.Nat;
export const ContactSubmission = IDL.Record({
  'id' : ContactSubmissionId,
  'name' : IDL.Text,
  'created_at' : Timestamp,
  'email' : IDL.Text,
  'company' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const Role = IDL.Variant({ 'member' : IDL.Null, 'admin' : IDL.Null });
export const UserPublic = IDL.Record({
  'principal' : UserId,
  'name' : IDL.Text,
  'role' : Role,
  'created_at' : Timestamp,
  'email' : IDL.Text,
});
export const PaginatedResult_6 = IDL.Record({
  'total' : IDL.Nat,
  'items' : IDL.Vec(ClientPublic),
});
export const PaginatedResult_5 = IDL.Record({
  'total' : IDL.Nat,
  'items' : IDL.Vec(ContactSubmission),
});
export const PaginatedResult_4 = IDL.Record({
  'total' : IDL.Nat,
  'items' : IDL.Vec(JobPostingPublic),
});
export const PaginatedResult_3 = IDL.Record({
  'total' : IDL.Nat,
  'items' : IDL.Vec(LeadPublic),
});
export const PaginatedResult_2 = IDL.Record({
  'total' : IDL.Nat,
  'items' : IDL.Vec(ProjectPublic),
});
export const PaginatedResult_1 = IDL.Record({
  'total' : IDL.Nat,
  'items' : IDL.Vec(TaskPublic),
});
export const PaginatedResult = IDL.Record({
  'total' : IDL.Nat,
  'items' : IDL.Vec(UserPublic),
});
export const CreateContactSubmissionPayload = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'company' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const UpdateClientPayload = IDL.Record({
  'status' : ClientStatus,
  'company_name' : IDL.Text,
  'email' : IDL.Text,
  'contact_name' : IDL.Text,
  'phone' : IDL.Text,
});
export const UpdateJobPostingPayload = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'is_active' : IDL.Bool,
  'department' : IDL.Text,
  'requirements' : IDL.Text,
  'location' : IDL.Text,
  'job_type' : JobType,
});
export const UpdateLeadPayload = IDL.Record({
  'status' : LeadStatus,
  'source' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'company' : IDL.Text,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
});
export const UpdateUserProfilePayload = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const UpdateProjectPayload = IDL.Record({
  'status' : ProjectStatus,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'end_date' : IDL.Text,
  'start_date' : IDL.Text,
  'progress' : IDL.Nat,
  'client_id' : ClientId,
  'budget' : IDL.Nat,
  'owner_principal' : UserId,
});
export const UpdateTaskPayload = IDL.Record({
  'status' : TaskStatus,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'assigned_to' : UserId,
  'due_date' : IDL.Text,
  'priority' : TaskPriority,
  'project_id' : ProjectId,
});

export const idlService = IDL.Service({
  'createClient' : IDL.Func([CreateClientPayload], [ClientPublic], []),
  'createJobPosting' : IDL.Func(
      [CreateJobPostingPayload],
      [JobPostingPublic],
      [],
    ),
  'createLead' : IDL.Func([CreateLeadPayload], [LeadPublic], []),
  'createProject' : IDL.Func([CreateProjectPayload], [ProjectPublic], []),
  'createTask' : IDL.Func([CreateTaskPayload], [TaskPublic], []),
  'deleteClient' : IDL.Func([ClientId], [IDL.Bool], []),
  'deleteContactSubmission' : IDL.Func([ContactSubmissionId], [IDL.Bool], []),
  'deleteJobPosting' : IDL.Func([JobPostingId], [IDL.Bool], []),
  'deleteLead' : IDL.Func([LeadId], [IDL.Bool], []),
  'deleteProject' : IDL.Func([ProjectId], [IDL.Bool], []),
  'deleteTask' : IDL.Func([TaskId], [IDL.Bool], []),
  'getClient' : IDL.Func([ClientId], [IDL.Opt(ClientPublic)], ['query']),
  'getContactSubmission' : IDL.Func(
      [ContactSubmissionId],
      [IDL.Opt(ContactSubmission)],
      ['query'],
    ),
  'getJobPosting' : IDL.Func(
      [JobPostingId],
      [IDL.Opt(JobPostingPublic)],
      ['query'],
    ),
  'getLead' : IDL.Func([LeadId], [IDL.Opt(LeadPublic)], ['query']),
  'getMe' : IDL.Func([], [IDL.Opt(UserPublic)], ['query']),
  'getProject' : IDL.Func([ProjectId], [IDL.Opt(ProjectPublic)], ['query']),
  'getTask' : IDL.Func([TaskId], [IDL.Opt(TaskPublic)], ['query']),
  'getUser' : IDL.Func([UserId], [IDL.Opt(UserPublic)], ['query']),
  'listClients' : IDL.Func(
      [IDL.Opt(ClientStatus), IDL.Nat, IDL.Nat],
      [PaginatedResult_6],
      ['query'],
    ),
  'listContactSubmissions' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [PaginatedResult_5],
      ['query'],
    ),
  'listJobPostings' : IDL.Func(
      [IDL.Opt(IDL.Bool), IDL.Nat, IDL.Nat],
      [PaginatedResult_4],
      ['query'],
    ),
  'listLeads' : IDL.Func(
      [IDL.Opt(LeadStatus), IDL.Nat, IDL.Nat],
      [PaginatedResult_3],
      ['query'],
    ),
  'listProjects' : IDL.Func(
      [IDL.Opt(ProjectStatus), IDL.Nat, IDL.Nat],
      [PaginatedResult_2],
      ['query'],
    ),
  'listTasks' : IDL.Func(
      [IDL.Opt(TaskStatus), IDL.Nat, IDL.Nat],
      [PaginatedResult_1],
      ['query'],
    ),
  'listUsers' : IDL.Func([IDL.Nat, IDL.Nat], [PaginatedResult], ['query']),
  'registerOrUpdateMe' : IDL.Func([IDL.Text, IDL.Text], [UserPublic], []),
  'setUserRole' : IDL.Func([UserId, Role], [IDL.Bool], []),
  'submitContactForm' : IDL.Func(
      [CreateContactSubmissionPayload],
      [ContactSubmission],
      [],
    ),
  'updateClient' : IDL.Func([ClientId, UpdateClientPayload], [IDL.Bool], []),
  'updateJobPosting' : IDL.Func(
      [JobPostingId, UpdateJobPostingPayload],
      [IDL.Bool],
      [],
    ),
  'updateLead' : IDL.Func([LeadId, UpdateLeadPayload], [IDL.Bool], []),
  'updateMyProfile' : IDL.Func([UpdateUserProfilePayload], [IDL.Bool], []),
  'updateProject' : IDL.Func([ProjectId, UpdateProjectPayload], [IDL.Bool], []),
  'updateTask' : IDL.Func([TaskId, UpdateTaskPayload], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ClientStatus = IDL.Variant({
    'Inactive' : IDL.Null,
    'Prospect' : IDL.Null,
    'Active' : IDL.Null,
  });
  const CreateClientPayload = IDL.Record({
    'status' : ClientStatus,
    'company_name' : IDL.Text,
    'email' : IDL.Text,
    'contact_name' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ClientId = IDL.Nat;
  const Timestamp = IDL.Int;
  const ClientPublic = IDL.Record({
    'id' : ClientId,
    'status' : ClientStatus,
    'company_name' : IDL.Text,
    'created_at' : Timestamp,
    'email' : IDL.Text,
    'contact_name' : IDL.Text,
    'phone' : IDL.Text,
  });
  const JobType = IDL.Variant({
    'Contract' : IDL.Null,
    'PartTime' : IDL.Null,
    'FullTime' : IDL.Null,
  });
  const CreateJobPostingPayload = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'is_active' : IDL.Bool,
    'department' : IDL.Text,
    'requirements' : IDL.Text,
    'location' : IDL.Text,
    'job_type' : JobType,
  });
  const JobPostingId = IDL.Nat;
  const JobPostingPublic = IDL.Record({
    'id' : JobPostingId,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'created_at' : Timestamp,
    'is_active' : IDL.Bool,
    'department' : IDL.Text,
    'requirements' : IDL.Text,
    'location' : IDL.Text,
    'job_type' : JobType,
  });
  const LeadStatus = IDL.Variant({
    'New' : IDL.Null,
    'Closed' : IDL.Null,
    'Contacted' : IDL.Null,
    'Qualified' : IDL.Null,
  });
  const CreateLeadPayload = IDL.Record({
    'status' : LeadStatus,
    'source' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'company' : IDL.Text,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
  });
  const LeadId = IDL.Nat;
  const LeadPublic = IDL.Record({
    'id' : LeadId,
    'status' : LeadStatus,
    'updated_at' : Timestamp,
    'source' : IDL.Text,
    'name' : IDL.Text,
    'created_at' : Timestamp,
    'email' : IDL.Text,
    'company' : IDL.Text,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ProjectStatus = IDL.Variant({
    'OnHold' : IDL.Null,
    'Planning' : IDL.Null,
    'InProgress' : IDL.Null,
    'Completed' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const CreateProjectPayload = IDL.Record({
    'status' : ProjectStatus,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'end_date' : IDL.Text,
    'start_date' : IDL.Text,
    'progress' : IDL.Nat,
    'client_id' : ClientId,
    'budget' : IDL.Nat,
    'owner_principal' : UserId,
  });
  const ProjectId = IDL.Nat;
  const ProjectPublic = IDL.Record({
    'id' : ProjectId,
    'status' : ProjectStatus,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'end_date' : IDL.Text,
    'created_at' : Timestamp,
    'start_date' : IDL.Text,
    'progress' : IDL.Nat,
    'client_id' : ClientId,
    'budget' : IDL.Nat,
    'owner_principal' : UserId,
  });
  const TaskStatus = IDL.Variant({
    'Done' : IDL.Null,
    'ToDo' : IDL.Null,
    'InProgress' : IDL.Null,
  });
  const TaskPriority = IDL.Variant({
    'Low' : IDL.Null,
    'High' : IDL.Null,
    'Medium' : IDL.Null,
  });
  const CreateTaskPayload = IDL.Record({
    'status' : TaskStatus,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'assigned_to' : UserId,
    'due_date' : IDL.Text,
    'priority' : TaskPriority,
    'project_id' : ProjectId,
  });
  const TaskId = IDL.Nat;
  const TaskPublic = IDL.Record({
    'id' : TaskId,
    'status' : TaskStatus,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'created_at' : Timestamp,
    'assigned_to' : UserId,
    'due_date' : IDL.Text,
    'priority' : TaskPriority,
    'project_id' : ProjectId,
  });
  const ContactSubmissionId = IDL.Nat;
  const ContactSubmission = IDL.Record({
    'id' : ContactSubmissionId,
    'name' : IDL.Text,
    'created_at' : Timestamp,
    'email' : IDL.Text,
    'company' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Role = IDL.Variant({ 'member' : IDL.Null, 'admin' : IDL.Null });
  const UserPublic = IDL.Record({
    'principal' : UserId,
    'name' : IDL.Text,
    'role' : Role,
    'created_at' : Timestamp,
    'email' : IDL.Text,
  });
  const PaginatedResult_6 = IDL.Record({
    'total' : IDL.Nat,
    'items' : IDL.Vec(ClientPublic),
  });
  const PaginatedResult_5 = IDL.Record({
    'total' : IDL.Nat,
    'items' : IDL.Vec(ContactSubmission),
  });
  const PaginatedResult_4 = IDL.Record({
    'total' : IDL.Nat,
    'items' : IDL.Vec(JobPostingPublic),
  });
  const PaginatedResult_3 = IDL.Record({
    'total' : IDL.Nat,
    'items' : IDL.Vec(LeadPublic),
  });
  const PaginatedResult_2 = IDL.Record({
    'total' : IDL.Nat,
    'items' : IDL.Vec(ProjectPublic),
  });
  const PaginatedResult_1 = IDL.Record({
    'total' : IDL.Nat,
    'items' : IDL.Vec(TaskPublic),
  });
  const PaginatedResult = IDL.Record({
    'total' : IDL.Nat,
    'items' : IDL.Vec(UserPublic),
  });
  const CreateContactSubmissionPayload = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'company' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const UpdateClientPayload = IDL.Record({
    'status' : ClientStatus,
    'company_name' : IDL.Text,
    'email' : IDL.Text,
    'contact_name' : IDL.Text,
    'phone' : IDL.Text,
  });
  const UpdateJobPostingPayload = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'is_active' : IDL.Bool,
    'department' : IDL.Text,
    'requirements' : IDL.Text,
    'location' : IDL.Text,
    'job_type' : JobType,
  });
  const UpdateLeadPayload = IDL.Record({
    'status' : LeadStatus,
    'source' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'company' : IDL.Text,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
  });
  const UpdateUserProfilePayload = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
  });
  const UpdateProjectPayload = IDL.Record({
    'status' : ProjectStatus,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'end_date' : IDL.Text,
    'start_date' : IDL.Text,
    'progress' : IDL.Nat,
    'client_id' : ClientId,
    'budget' : IDL.Nat,
    'owner_principal' : UserId,
  });
  const UpdateTaskPayload = IDL.Record({
    'status' : TaskStatus,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'assigned_to' : UserId,
    'due_date' : IDL.Text,
    'priority' : TaskPriority,
    'project_id' : ProjectId,
  });
  
  return IDL.Service({
    'createClient' : IDL.Func([CreateClientPayload], [ClientPublic], []),
    'createJobPosting' : IDL.Func(
        [CreateJobPostingPayload],
        [JobPostingPublic],
        [],
      ),
    'createLead' : IDL.Func([CreateLeadPayload], [LeadPublic], []),
    'createProject' : IDL.Func([CreateProjectPayload], [ProjectPublic], []),
    'createTask' : IDL.Func([CreateTaskPayload], [TaskPublic], []),
    'deleteClient' : IDL.Func([ClientId], [IDL.Bool], []),
    'deleteContactSubmission' : IDL.Func([ContactSubmissionId], [IDL.Bool], []),
    'deleteJobPosting' : IDL.Func([JobPostingId], [IDL.Bool], []),
    'deleteLead' : IDL.Func([LeadId], [IDL.Bool], []),
    'deleteProject' : IDL.Func([ProjectId], [IDL.Bool], []),
    'deleteTask' : IDL.Func([TaskId], [IDL.Bool], []),
    'getClient' : IDL.Func([ClientId], [IDL.Opt(ClientPublic)], ['query']),
    'getContactSubmission' : IDL.Func(
        [ContactSubmissionId],
        [IDL.Opt(ContactSubmission)],
        ['query'],
      ),
    'getJobPosting' : IDL.Func(
        [JobPostingId],
        [IDL.Opt(JobPostingPublic)],
        ['query'],
      ),
    'getLead' : IDL.Func([LeadId], [IDL.Opt(LeadPublic)], ['query']),
    'getMe' : IDL.Func([], [IDL.Opt(UserPublic)], ['query']),
    'getProject' : IDL.Func([ProjectId], [IDL.Opt(ProjectPublic)], ['query']),
    'getTask' : IDL.Func([TaskId], [IDL.Opt(TaskPublic)], ['query']),
    'getUser' : IDL.Func([UserId], [IDL.Opt(UserPublic)], ['query']),
    'listClients' : IDL.Func(
        [IDL.Opt(ClientStatus), IDL.Nat, IDL.Nat],
        [PaginatedResult_6],
        ['query'],
      ),
    'listContactSubmissions' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [PaginatedResult_5],
        ['query'],
      ),
    'listJobPostings' : IDL.Func(
        [IDL.Opt(IDL.Bool), IDL.Nat, IDL.Nat],
        [PaginatedResult_4],
        ['query'],
      ),
    'listLeads' : IDL.Func(
        [IDL.Opt(LeadStatus), IDL.Nat, IDL.Nat],
        [PaginatedResult_3],
        ['query'],
      ),
    'listProjects' : IDL.Func(
        [IDL.Opt(ProjectStatus), IDL.Nat, IDL.Nat],
        [PaginatedResult_2],
        ['query'],
      ),
    'listTasks' : IDL.Func(
        [IDL.Opt(TaskStatus), IDL.Nat, IDL.Nat],
        [PaginatedResult_1],
        ['query'],
      ),
    'listUsers' : IDL.Func([IDL.Nat, IDL.Nat], [PaginatedResult], ['query']),
    'registerOrUpdateMe' : IDL.Func([IDL.Text, IDL.Text], [UserPublic], []),
    'setUserRole' : IDL.Func([UserId, Role], [IDL.Bool], []),
    'submitContactForm' : IDL.Func(
        [CreateContactSubmissionPayload],
        [ContactSubmission],
        [],
      ),
    'updateClient' : IDL.Func([ClientId, UpdateClientPayload], [IDL.Bool], []),
    'updateJobPosting' : IDL.Func(
        [JobPostingId, UpdateJobPostingPayload],
        [IDL.Bool],
        [],
      ),
    'updateLead' : IDL.Func([LeadId, UpdateLeadPayload], [IDL.Bool], []),
    'updateMyProfile' : IDL.Func([UpdateUserProfilePayload], [IDL.Bool], []),
    'updateProject' : IDL.Func(
        [ProjectId, UpdateProjectPayload],
        [IDL.Bool],
        [],
      ),
    'updateTask' : IDL.Func([TaskId, UpdateTaskPayload], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };