/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ClientId = bigint;
export interface ClientPublic {
  'id' : ClientId,
  'status' : ClientStatus,
  'company_name' : string,
  'created_at' : Timestamp,
  'email' : string,
  'contact_name' : string,
  'phone' : string,
}
export type ClientStatus = { 'Inactive' : null } |
  { 'Prospect' : null } |
  { 'Active' : null };
export interface ContactSubmission {
  'id' : ContactSubmissionId,
  'name' : string,
  'created_at' : Timestamp,
  'email' : string,
  'company' : string,
  'message' : string,
  'phone' : string,
}
export type ContactSubmissionId = bigint;
export interface CreateClientPayload {
  'status' : ClientStatus,
  'company_name' : string,
  'email' : string,
  'contact_name' : string,
  'phone' : string,
}
export interface CreateContactSubmissionPayload {
  'name' : string,
  'email' : string,
  'company' : string,
  'message' : string,
  'phone' : string,
}
export interface CreateJobPostingPayload {
  'title' : string,
  'description' : string,
  'is_active' : boolean,
  'department' : string,
  'requirements' : string,
  'location' : string,
  'job_type' : JobType,
}
export interface CreateLeadPayload {
  'status' : LeadStatus,
  'source' : string,
  'name' : string,
  'email' : string,
  'company' : string,
  'notes' : string,
  'phone' : string,
}
export interface CreateProjectPayload {
  'status' : ProjectStatus,
  'name' : string,
  'description' : string,
  'end_date' : string,
  'start_date' : string,
  'progress' : bigint,
  'client_id' : ClientId,
  'budget' : bigint,
  'owner_principal' : UserId,
}
export interface CreateTaskPayload {
  'status' : TaskStatus,
  'title' : string,
  'description' : string,
  'assigned_to' : UserId,
  'due_date' : string,
  'priority' : TaskPriority,
  'project_id' : ProjectId,
}
export type JobPostingId = bigint;
export interface JobPostingPublic {
  'id' : JobPostingId,
  'title' : string,
  'description' : string,
  'created_at' : Timestamp,
  'is_active' : boolean,
  'department' : string,
  'requirements' : string,
  'location' : string,
  'job_type' : JobType,
}
export type JobType = { 'Contract' : null } |
  { 'PartTime' : null } |
  { 'FullTime' : null };
export type LeadId = bigint;
export interface LeadPublic {
  'id' : LeadId,
  'status' : LeadStatus,
  'updated_at' : Timestamp,
  'source' : string,
  'name' : string,
  'created_at' : Timestamp,
  'email' : string,
  'company' : string,
  'notes' : string,
  'phone' : string,
}
export type LeadStatus = { 'New' : null } |
  { 'Closed' : null } |
  { 'Contacted' : null } |
  { 'Qualified' : null };
export interface PaginatedResult {
  'total' : bigint,
  'items' : Array<UserPublic>,
}
export interface PaginatedResult_1 {
  'total' : bigint,
  'items' : Array<TaskPublic>,
}
export interface PaginatedResult_2 {
  'total' : bigint,
  'items' : Array<ProjectPublic>,
}
export interface PaginatedResult_3 {
  'total' : bigint,
  'items' : Array<LeadPublic>,
}
export interface PaginatedResult_4 {
  'total' : bigint,
  'items' : Array<JobPostingPublic>,
}
export interface PaginatedResult_5 {
  'total' : bigint,
  'items' : Array<ContactSubmission>,
}
export interface PaginatedResult_6 {
  'total' : bigint,
  'items' : Array<ClientPublic>,
}
export type ProjectId = bigint;
export interface ProjectPublic {
  'id' : ProjectId,
  'status' : ProjectStatus,
  'name' : string,
  'description' : string,
  'end_date' : string,
  'created_at' : Timestamp,
  'start_date' : string,
  'progress' : bigint,
  'client_id' : ClientId,
  'budget' : bigint,
  'owner_principal' : UserId,
}
export type ProjectStatus = { 'OnHold' : null } |
  { 'Planning' : null } |
  { 'InProgress' : null } |
  { 'Completed' : null };
export type Role = { 'member' : null } |
  { 'admin' : null };
export type TaskId = bigint;
export type TaskPriority = { 'Low' : null } |
  { 'High' : null } |
  { 'Medium' : null };
export interface TaskPublic {
  'id' : TaskId,
  'status' : TaskStatus,
  'title' : string,
  'description' : string,
  'created_at' : Timestamp,
  'assigned_to' : UserId,
  'due_date' : string,
  'priority' : TaskPriority,
  'project_id' : ProjectId,
}
export type TaskStatus = { 'Done' : null } |
  { 'ToDo' : null } |
  { 'InProgress' : null };
export type Timestamp = bigint;
export interface UpdateClientPayload {
  'status' : ClientStatus,
  'company_name' : string,
  'email' : string,
  'contact_name' : string,
  'phone' : string,
}
export interface UpdateJobPostingPayload {
  'title' : string,
  'description' : string,
  'is_active' : boolean,
  'department' : string,
  'requirements' : string,
  'location' : string,
  'job_type' : JobType,
}
export interface UpdateLeadPayload {
  'status' : LeadStatus,
  'source' : string,
  'name' : string,
  'email' : string,
  'company' : string,
  'notes' : string,
  'phone' : string,
}
export interface UpdateProjectPayload {
  'status' : ProjectStatus,
  'name' : string,
  'description' : string,
  'end_date' : string,
  'start_date' : string,
  'progress' : bigint,
  'client_id' : ClientId,
  'budget' : bigint,
  'owner_principal' : UserId,
}
export interface UpdateTaskPayload {
  'status' : TaskStatus,
  'title' : string,
  'description' : string,
  'assigned_to' : UserId,
  'due_date' : string,
  'priority' : TaskPriority,
  'project_id' : ProjectId,
}
export interface UpdateUserProfilePayload { 'name' : string, 'email' : string }
export type UserId = Principal;
export interface UserPublic {
  'principal' : UserId,
  'name' : string,
  'role' : Role,
  'created_at' : Timestamp,
  'email' : string,
}
export interface _SERVICE {
  'createClient' : ActorMethod<[CreateClientPayload], ClientPublic>,
  'createJobPosting' : ActorMethod<[CreateJobPostingPayload], JobPostingPublic>,
  'createLead' : ActorMethod<[CreateLeadPayload], LeadPublic>,
  'createProject' : ActorMethod<[CreateProjectPayload], ProjectPublic>,
  'createTask' : ActorMethod<[CreateTaskPayload], TaskPublic>,
  'deleteClient' : ActorMethod<[ClientId], boolean>,
  'deleteContactSubmission' : ActorMethod<[ContactSubmissionId], boolean>,
  'deleteJobPosting' : ActorMethod<[JobPostingId], boolean>,
  'deleteLead' : ActorMethod<[LeadId], boolean>,
  'deleteProject' : ActorMethod<[ProjectId], boolean>,
  'deleteTask' : ActorMethod<[TaskId], boolean>,
  'getClient' : ActorMethod<[ClientId], [] | [ClientPublic]>,
  'getContactSubmission' : ActorMethod<
    [ContactSubmissionId],
    [] | [ContactSubmission]
  >,
  'getJobPosting' : ActorMethod<[JobPostingId], [] | [JobPostingPublic]>,
  'getLead' : ActorMethod<[LeadId], [] | [LeadPublic]>,
  'getMe' : ActorMethod<[], [] | [UserPublic]>,
  'getProject' : ActorMethod<[ProjectId], [] | [ProjectPublic]>,
  'getTask' : ActorMethod<[TaskId], [] | [TaskPublic]>,
  'getUser' : ActorMethod<[UserId], [] | [UserPublic]>,
  'listClients' : ActorMethod<
    [[] | [ClientStatus], bigint, bigint],
    PaginatedResult_6
  >,
  'listContactSubmissions' : ActorMethod<[bigint, bigint], PaginatedResult_5>,
  'listJobPostings' : ActorMethod<
    [[] | [boolean], bigint, bigint],
    PaginatedResult_4
  >,
  'listLeads' : ActorMethod<
    [[] | [LeadStatus], bigint, bigint],
    PaginatedResult_3
  >,
  'listProjects' : ActorMethod<
    [[] | [ProjectStatus], bigint, bigint],
    PaginatedResult_2
  >,
  'listTasks' : ActorMethod<
    [[] | [TaskStatus], bigint, bigint],
    PaginatedResult_1
  >,
  'listUsers' : ActorMethod<[bigint, bigint], PaginatedResult>,
  'registerOrUpdateMe' : ActorMethod<[string, string], UserPublic>,
  'setUserRole' : ActorMethod<[UserId, Role], boolean>,
  'submitContactForm' : ActorMethod<
    [CreateContactSubmissionPayload],
    ContactSubmission
  >,
  'updateClient' : ActorMethod<[ClientId, UpdateClientPayload], boolean>,
  'updateJobPosting' : ActorMethod<
    [JobPostingId, UpdateJobPostingPayload],
    boolean
  >,
  'updateLead' : ActorMethod<[LeadId, UpdateLeadPayload], boolean>,
  'updateMyProfile' : ActorMethod<[UpdateUserProfilePayload], boolean>,
  'updateProject' : ActorMethod<[ProjectId, UpdateProjectPayload], boolean>,
  'updateTask' : ActorMethod<[TaskId, UpdateTaskPayload], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];