/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UpdateTaskPayload {
    status: TaskStatus;
    title: string;
    description: string;
    assigned_to: UserId;
    due_date: string;
    priority: TaskPriority;
    project_id: ProjectId;
}
export type Timestamp = bigint;
export interface UserPublic {
    principal: UserId;
    name: string;
    role: Role;
    created_at: Timestamp;
    email: string;
}
export interface PaginatedResult_6 {
    total: bigint;
    items: Array<ClientPublic>;
}
export interface PaginatedResult_1 {
    total: bigint;
    items: Array<TaskPublic>;
}
export interface LeadPublic {
    id: LeadId;
    status: LeadStatus;
    updated_at: Timestamp;
    source: string;
    name: string;
    created_at: Timestamp;
    email: string;
    company: string;
    notes: string;
    phone: string;
}
export type LeadId = bigint;
export interface CreateContactSubmissionPayload {
    name: string;
    email: string;
    company: string;
    message: string;
    phone: string;
}
export type ContactSubmissionId = bigint;
export interface PaginatedResult_2 {
    total: bigint;
    items: Array<ProjectPublic>;
}
export interface ContactSubmission {
    id: ContactSubmissionId;
    name: string;
    created_at: Timestamp;
    email: string;
    company: string;
    message: string;
    phone: string;
}
export interface UpdateClientPayload {
    status: ClientStatus;
    company_name: string;
    email: string;
    contact_name: string;
    phone: string;
}
export interface CreateJobPostingPayload {
    title: string;
    description: string;
    is_active: boolean;
    department: string;
    requirements: string;
    location: string;
    job_type: JobType;
}
export interface PaginatedResult_5 {
    total: bigint;
    items: Array<ContactSubmission>;
}
export interface ProjectPublic {
    id: ProjectId;
    status: ProjectStatus;
    name: string;
    description: string;
    end_date: string;
    created_at: Timestamp;
    start_date: string;
    progress: bigint;
    client_id: ClientId;
    budget: bigint;
    owner_principal: UserId;
}
export interface TaskPublic {
    id: TaskId;
    status: TaskStatus;
    title: string;
    description: string;
    created_at: Timestamp;
    assigned_to: UserId;
    due_date: string;
    priority: TaskPriority;
    project_id: ProjectId;
}
export interface PaginatedResult {
    total: bigint;
    items: Array<UserPublic>;
}
export type JobPostingId = bigint;
export interface ClientPublic {
    id: ClientId;
    status: ClientStatus;
    company_name: string;
    created_at: Timestamp;
    email: string;
    contact_name: string;
    phone: string;
}
export interface JobPostingPublic {
    id: JobPostingId;
    title: string;
    description: string;
    created_at: Timestamp;
    is_active: boolean;
    department: string;
    requirements: string;
    location: string;
    job_type: JobType;
}
export interface UpdateUserProfilePayload {
    name: string;
    email: string;
}
export type ClientId = bigint;
export interface CreateProjectPayload {
    status: ProjectStatus;
    name: string;
    description: string;
    end_date: string;
    start_date: string;
    progress: bigint;
    client_id: ClientId;
    budget: bigint;
    owner_principal: UserId;
}
export interface UpdateJobPostingPayload {
    title: string;
    description: string;
    is_active: boolean;
    department: string;
    requirements: string;
    location: string;
    job_type: JobType;
}
export interface CreateTaskPayload {
    status: TaskStatus;
    title: string;
    description: string;
    assigned_to: UserId;
    due_date: string;
    priority: TaskPriority;
    project_id: ProjectId;
}
export interface UpdateProjectPayload {
    status: ProjectStatus;
    name: string;
    description: string;
    end_date: string;
    start_date: string;
    progress: bigint;
    client_id: ClientId;
    budget: bigint;
    owner_principal: UserId;
}
export interface UpdateLeadPayload {
    status: LeadStatus;
    source: string;
    name: string;
    email: string;
    company: string;
    notes: string;
    phone: string;
}
export type UserId = Principal;
export interface PaginatedResult_3 {
    total: bigint;
    items: Array<LeadPublic>;
}
export type TaskId = bigint;
export type ProjectId = bigint;
export interface CreateClientPayload {
    status: ClientStatus;
    company_name: string;
    email: string;
    contact_name: string;
    phone: string;
}
export interface PaginatedResult_4 {
    total: bigint;
    items: Array<JobPostingPublic>;
}
export interface CreateLeadPayload {
    status: LeadStatus;
    source: string;
    name: string;
    email: string;
    company: string;
    notes: string;
    phone: string;
}
export enum ClientStatus {
    Inactive = "Inactive",
    Prospect = "Prospect",
    Active = "Active"
}
export enum JobType {
    Contract = "Contract",
    PartTime = "PartTime",
    FullTime = "FullTime"
}
export enum LeadStatus {
    New = "New",
    Closed = "Closed",
    Contacted = "Contacted",
    Qualified = "Qualified"
}
export enum ProjectStatus {
    OnHold = "OnHold",
    Planning = "Planning",
    InProgress = "InProgress",
    Completed = "Completed"
}
export enum Role {
    member = "member",
    admin = "admin"
}
export enum TaskPriority {
    Low = "Low",
    High = "High",
    Medium = "Medium"
}
export enum TaskStatus {
    Done = "Done",
    ToDo = "ToDo",
    InProgress = "InProgress"
}
export interface backendInterface {
    createClient(payload: CreateClientPayload): Promise<ClientPublic>;
    createJobPosting(payload: CreateJobPostingPayload): Promise<JobPostingPublic>;
    createLead(payload: CreateLeadPayload): Promise<LeadPublic>;
    createProject(payload: CreateProjectPayload): Promise<ProjectPublic>;
    createTask(payload: CreateTaskPayload): Promise<TaskPublic>;
    deleteClient(id: ClientId): Promise<boolean>;
    deleteContactSubmission(id: ContactSubmissionId): Promise<boolean>;
    deleteJobPosting(id: JobPostingId): Promise<boolean>;
    deleteLead(id: LeadId): Promise<boolean>;
    deleteProject(id: ProjectId): Promise<boolean>;
    deleteTask(id: TaskId): Promise<boolean>;
    getClient(id: ClientId): Promise<ClientPublic | null>;
    getContactSubmission(id: ContactSubmissionId): Promise<ContactSubmission | null>;
    getJobPosting(id: JobPostingId): Promise<JobPostingPublic | null>;
    getLead(id: LeadId): Promise<LeadPublic | null>;
    getMe(): Promise<UserPublic | null>;
    getProject(id: ProjectId): Promise<ProjectPublic | null>;
    getTask(id: TaskId): Promise<TaskPublic | null>;
    getUser(principal: UserId): Promise<UserPublic | null>;
    listClients(statusFilter: ClientStatus | null, offset: bigint, limit: bigint): Promise<PaginatedResult_6>;
    listContactSubmissions(offset: bigint, limit: bigint): Promise<PaginatedResult_5>;
    listJobPostings(activeOnly: boolean | null, offset: bigint, limit: bigint): Promise<PaginatedResult_4>;
    listLeads(statusFilter: LeadStatus | null, offset: bigint, limit: bigint): Promise<PaginatedResult_3>;
    listProjects(statusFilter: ProjectStatus | null, offset: bigint, limit: bigint): Promise<PaginatedResult_2>;
    listTasks(statusFilter: TaskStatus | null, offset: bigint, limit: bigint): Promise<PaginatedResult_1>;
    listUsers(offset: bigint, limit: bigint): Promise<PaginatedResult>;
    registerOrUpdateMe(name: string, email: string): Promise<UserPublic>;
    setUserRole(principal: UserId, role: Role): Promise<boolean>;
    submitContactForm(payload: CreateContactSubmissionPayload): Promise<ContactSubmission>;
    updateClient(id: ClientId, payload: UpdateClientPayload): Promise<boolean>;
    updateJobPosting(id: JobPostingId, payload: UpdateJobPostingPayload): Promise<boolean>;
    updateLead(id: LeadId, payload: UpdateLeadPayload): Promise<boolean>;
    updateMyProfile(payload: UpdateUserProfilePayload): Promise<boolean>;
    updateProject(id: ProjectId, payload: UpdateProjectPayload): Promise<boolean>;
    updateTask(id: TaskId, payload: UpdateTaskPayload): Promise<boolean>;
}
import type { ClientId as _ClientId, ClientPublic as _ClientPublic, ClientStatus as _ClientStatus, ContactSubmission as _ContactSubmission, CreateClientPayload as _CreateClientPayload, CreateJobPostingPayload as _CreateJobPostingPayload, CreateLeadPayload as _CreateLeadPayload, CreateProjectPayload as _CreateProjectPayload, CreateTaskPayload as _CreateTaskPayload, JobPostingId as _JobPostingId, JobPostingPublic as _JobPostingPublic, JobType as _JobType, LeadId as _LeadId, LeadPublic as _LeadPublic, LeadStatus as _LeadStatus, PaginatedResult as _PaginatedResult, PaginatedResult_1 as _PaginatedResult_1, PaginatedResult_2 as _PaginatedResult_2, PaginatedResult_3 as _PaginatedResult_3, PaginatedResult_4 as _PaginatedResult_4, PaginatedResult_6 as _PaginatedResult_6, ProjectId as _ProjectId, ProjectPublic as _ProjectPublic, ProjectStatus as _ProjectStatus, Role as _Role, TaskId as _TaskId, TaskPriority as _TaskPriority, TaskPublic as _TaskPublic, TaskStatus as _TaskStatus, Timestamp as _Timestamp, UpdateClientPayload as _UpdateClientPayload, UpdateJobPostingPayload as _UpdateJobPostingPayload, UpdateLeadPayload as _UpdateLeadPayload, UpdateProjectPayload as _UpdateProjectPayload, UpdateTaskPayload as _UpdateTaskPayload, UserId as _UserId, UserPublic as _UserPublic } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createClient(arg0: CreateClientPayload): Promise<ClientPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.createClient(to_candid_CreateClientPayload_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_ClientPublic_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createClient(to_candid_CreateClientPayload_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_ClientPublic_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async createJobPosting(arg0: CreateJobPostingPayload): Promise<JobPostingPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.createJobPosting(to_candid_CreateJobPostingPayload_n9(this._uploadFile, this._downloadFile, arg0));
                return from_candid_JobPostingPublic_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createJobPosting(to_candid_CreateJobPostingPayload_n9(this._uploadFile, this._downloadFile, arg0));
            return from_candid_JobPostingPublic_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async createLead(arg0: CreateLeadPayload): Promise<LeadPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.createLead(to_candid_CreateLeadPayload_n17(this._uploadFile, this._downloadFile, arg0));
                return from_candid_LeadPublic_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLead(to_candid_CreateLeadPayload_n17(this._uploadFile, this._downloadFile, arg0));
            return from_candid_LeadPublic_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async createProject(arg0: CreateProjectPayload): Promise<ProjectPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.createProject(to_candid_CreateProjectPayload_n25(this._uploadFile, this._downloadFile, arg0));
                return from_candid_ProjectPublic_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProject(to_candid_CreateProjectPayload_n25(this._uploadFile, this._downloadFile, arg0));
            return from_candid_ProjectPublic_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async createTask(arg0: CreateTaskPayload): Promise<TaskPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.createTask(to_candid_CreateTaskPayload_n33(this._uploadFile, this._downloadFile, arg0));
                return from_candid_TaskPublic_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTask(to_candid_CreateTaskPayload_n33(this._uploadFile, this._downloadFile, arg0));
            return from_candid_TaskPublic_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteClient(arg0: ClientId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteClient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteClient(arg0);
            return result;
        }
    }
    async deleteContactSubmission(arg0: ContactSubmissionId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteContactSubmission(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteContactSubmission(arg0);
            return result;
        }
    }
    async deleteJobPosting(arg0: JobPostingId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteJobPosting(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteJobPosting(arg0);
            return result;
        }
    }
    async deleteLead(arg0: LeadId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLead(arg0);
            return result;
        }
    }
    async deleteProject(arg0: ProjectId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProject(arg0);
            return result;
        }
    }
    async deleteTask(arg0: TaskId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTask(arg0);
            return result;
        }
    }
    async getClient(arg0: ClientId): Promise<ClientPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getClient(arg0);
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClient(arg0);
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContactSubmission(arg0: ContactSubmissionId): Promise<ContactSubmission | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getContactSubmission(arg0);
                return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContactSubmission(arg0);
            return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobPosting(arg0: JobPostingId): Promise<JobPostingPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobPosting(arg0);
                return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobPosting(arg0);
            return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLead(arg0: LeadId): Promise<LeadPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLead(arg0);
                return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLead(arg0);
            return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMe(): Promise<UserPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMe();
                return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMe();
            return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProject(arg0: ProjectId): Promise<ProjectPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProject(arg0);
                return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProject(arg0);
            return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTask(arg0: TaskId): Promise<TaskPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTask(arg0);
                return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTask(arg0);
            return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUser(arg0: UserId): Promise<UserPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUser(arg0);
                return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUser(arg0);
            return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async listClients(arg0: ClientStatus | null, arg1: bigint, arg2: bigint): Promise<PaginatedResult_6> {
        if (this.processError) {
            try {
                const result = await this.actor.listClients(to_candid_opt_n56(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return from_candid_PaginatedResult_6_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listClients(to_candid_opt_n56(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return from_candid_PaginatedResult_6_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async listContactSubmissions(arg0: bigint, arg1: bigint): Promise<PaginatedResult_5> {
        if (this.processError) {
            try {
                const result = await this.actor.listContactSubmissions(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listContactSubmissions(arg0, arg1);
            return result;
        }
    }
    async listJobPostings(arg0: boolean | null, arg1: bigint, arg2: bigint): Promise<PaginatedResult_4> {
        if (this.processError) {
            try {
                const result = await this.actor.listJobPostings(to_candid_opt_n60(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return from_candid_PaginatedResult_4_n61(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listJobPostings(to_candid_opt_n60(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return from_candid_PaginatedResult_4_n61(this._uploadFile, this._downloadFile, result);
        }
    }
    async listLeads(arg0: LeadStatus | null, arg1: bigint, arg2: bigint): Promise<PaginatedResult_3> {
        if (this.processError) {
            try {
                const result = await this.actor.listLeads(to_candid_opt_n64(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return from_candid_PaginatedResult_3_n65(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listLeads(to_candid_opt_n64(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return from_candid_PaginatedResult_3_n65(this._uploadFile, this._downloadFile, result);
        }
    }
    async listProjects(arg0: ProjectStatus | null, arg1: bigint, arg2: bigint): Promise<PaginatedResult_2> {
        if (this.processError) {
            try {
                const result = await this.actor.listProjects(to_candid_opt_n68(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return from_candid_PaginatedResult_2_n69(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProjects(to_candid_opt_n68(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return from_candid_PaginatedResult_2_n69(this._uploadFile, this._downloadFile, result);
        }
    }
    async listTasks(arg0: TaskStatus | null, arg1: bigint, arg2: bigint): Promise<PaginatedResult_1> {
        if (this.processError) {
            try {
                const result = await this.actor.listTasks(to_candid_opt_n72(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return from_candid_PaginatedResult_1_n73(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTasks(to_candid_opt_n72(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return from_candid_PaginatedResult_1_n73(this._uploadFile, this._downloadFile, result);
        }
    }
    async listUsers(arg0: bigint, arg1: bigint): Promise<PaginatedResult> {
        if (this.processError) {
            try {
                const result = await this.actor.listUsers(arg0, arg1);
                return from_candid_PaginatedResult_n76(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listUsers(arg0, arg1);
            return from_candid_PaginatedResult_n76(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerOrUpdateMe(arg0: string, arg1: string): Promise<UserPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.registerOrUpdateMe(arg0, arg1);
                return from_candid_UserPublic_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerOrUpdateMe(arg0, arg1);
            return from_candid_UserPublic_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async setUserRole(arg0: UserId, arg1: Role): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setUserRole(arg0, to_candid_Role_n79(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUserRole(arg0, to_candid_Role_n79(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async submitContactForm(arg0: CreateContactSubmissionPayload): Promise<ContactSubmission> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContactForm(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContactForm(arg0);
            return result;
        }
    }
    async updateClient(arg0: ClientId, arg1: UpdateClientPayload): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateClient(arg0, to_candid_UpdateClientPayload_n81(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateClient(arg0, to_candid_UpdateClientPayload_n81(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateJobPosting(arg0: JobPostingId, arg1: UpdateJobPostingPayload): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateJobPosting(arg0, to_candid_UpdateJobPostingPayload_n82(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateJobPosting(arg0, to_candid_UpdateJobPostingPayload_n82(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateLead(arg0: LeadId, arg1: UpdateLeadPayload): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLead(arg0, to_candid_UpdateLeadPayload_n83(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLead(arg0, to_candid_UpdateLeadPayload_n83(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateMyProfile(arg0: UpdateUserProfilePayload): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMyProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMyProfile(arg0);
            return result;
        }
    }
    async updateProject(arg0: ProjectId, arg1: UpdateProjectPayload): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProject(arg0, to_candid_UpdateProjectPayload_n84(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProject(arg0, to_candid_UpdateProjectPayload_n84(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateTask(arg0: TaskId, arg1: UpdateTaskPayload): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTask(arg0, to_candid_UpdateTaskPayload_n85(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTask(arg0, to_candid_UpdateTaskPayload_n85(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_ClientPublic_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ClientPublic): ClientPublic {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_ClientStatus_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ClientStatus): ClientStatus {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_JobPostingPublic_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobPostingPublic): JobPostingPublic {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_JobType_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobType): JobType {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_LeadPublic_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LeadPublic): LeadPublic {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_LeadStatus_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LeadStatus): LeadStatus {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_PaginatedResult_1_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaginatedResult_1): PaginatedResult_1 {
    return from_candid_record_n74(_uploadFile, _downloadFile, value);
}
function from_candid_PaginatedResult_2_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaginatedResult_2): PaginatedResult_2 {
    return from_candid_record_n70(_uploadFile, _downloadFile, value);
}
function from_candid_PaginatedResult_3_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaginatedResult_3): PaginatedResult_3 {
    return from_candid_record_n66(_uploadFile, _downloadFile, value);
}
function from_candid_PaginatedResult_4_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaginatedResult_4): PaginatedResult_4 {
    return from_candid_record_n62(_uploadFile, _downloadFile, value);
}
function from_candid_PaginatedResult_6_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaginatedResult_6): PaginatedResult_6 {
    return from_candid_record_n58(_uploadFile, _downloadFile, value);
}
function from_candid_PaginatedResult_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaginatedResult): PaginatedResult {
    return from_candid_record_n77(_uploadFile, _downloadFile, value);
}
function from_candid_ProjectPublic_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProjectPublic): ProjectPublic {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_ProjectStatus_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProjectStatus): ProjectStatus {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n53(_uploadFile, _downloadFile, value);
}
function from_candid_TaskPriority_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskPriority): TaskPriority {
    return from_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function from_candid_TaskPublic_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskPublic): TaskPublic {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_TaskStatus_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskStatus): TaskStatus {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid_UserPublic_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserPublic): UserPublic {
    return from_candid_record_n51(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ClientPublic]): ClientPublic | null {
    return value.length === 0 ? null : from_candid_ClientPublic_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ContactSubmission]): ContactSubmission | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_JobPostingPublic]): JobPostingPublic | null {
    return value.length === 0 ? null : from_candid_JobPostingPublic_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LeadPublic]): LeadPublic | null {
    return value.length === 0 ? null : from_candid_LeadPublic_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserPublic]): UserPublic | null {
    return value.length === 0 ? null : from_candid_UserPublic_n50(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ProjectPublic]): ProjectPublic | null {
    return value.length === 0 ? null : from_candid_ProjectPublic_n29(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TaskPublic]): TaskPublic | null {
    return value.length === 0 ? null : from_candid_TaskPublic_n39(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _JobPostingId;
    title: string;
    description: string;
    created_at: _Timestamp;
    is_active: boolean;
    department: string;
    requirements: string;
    location: string;
    job_type: _JobType;
}): {
    id: JobPostingId;
    title: string;
    description: string;
    created_at: Timestamp;
    is_active: boolean;
    department: string;
    requirements: string;
    location: string;
    job_type: JobType;
} {
    return {
        id: value.id,
        title: value.title,
        description: value.description,
        created_at: value.created_at,
        is_active: value.is_active,
        department: value.department,
        requirements: value.requirements,
        location: value.location,
        job_type: from_candid_JobType_n15(_uploadFile, _downloadFile, value.job_type)
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _LeadId;
    status: _LeadStatus;
    updated_at: _Timestamp;
    source: string;
    name: string;
    created_at: _Timestamp;
    email: string;
    company: string;
    notes: string;
    phone: string;
}): {
    id: LeadId;
    status: LeadStatus;
    updated_at: Timestamp;
    source: string;
    name: string;
    created_at: Timestamp;
    email: string;
    company: string;
    notes: string;
    phone: string;
} {
    return {
        id: value.id,
        status: from_candid_LeadStatus_n23(_uploadFile, _downloadFile, value.status),
        updated_at: value.updated_at,
        source: value.source,
        name: value.name,
        created_at: value.created_at,
        email: value.email,
        company: value.company,
        notes: value.notes,
        phone: value.phone
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ProjectId;
    status: _ProjectStatus;
    name: string;
    description: string;
    end_date: string;
    created_at: _Timestamp;
    start_date: string;
    progress: bigint;
    client_id: _ClientId;
    budget: bigint;
    owner_principal: _UserId;
}): {
    id: ProjectId;
    status: ProjectStatus;
    name: string;
    description: string;
    end_date: string;
    created_at: Timestamp;
    start_date: string;
    progress: bigint;
    client_id: ClientId;
    budget: bigint;
    owner_principal: UserId;
} {
    return {
        id: value.id,
        status: from_candid_ProjectStatus_n31(_uploadFile, _downloadFile, value.status),
        name: value.name,
        description: value.description,
        end_date: value.end_date,
        created_at: value.created_at,
        start_date: value.start_date,
        progress: value.progress,
        client_id: value.client_id,
        budget: value.budget,
        owner_principal: value.owner_principal
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TaskId;
    status: _TaskStatus;
    title: string;
    description: string;
    created_at: _Timestamp;
    assigned_to: _UserId;
    due_date: string;
    priority: _TaskPriority;
    project_id: _ProjectId;
}): {
    id: TaskId;
    status: TaskStatus;
    title: string;
    description: string;
    created_at: Timestamp;
    assigned_to: UserId;
    due_date: string;
    priority: TaskPriority;
    project_id: ProjectId;
} {
    return {
        id: value.id,
        status: from_candid_TaskStatus_n41(_uploadFile, _downloadFile, value.status),
        title: value.title,
        description: value.description,
        created_at: value.created_at,
        assigned_to: value.assigned_to,
        due_date: value.due_date,
        priority: from_candid_TaskPriority_n43(_uploadFile, _downloadFile, value.priority),
        project_id: value.project_id
    };
}
function from_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: _UserId;
    name: string;
    role: _Role;
    created_at: _Timestamp;
    email: string;
}): {
    principal: UserId;
    name: string;
    role: Role;
    created_at: Timestamp;
    email: string;
} {
    return {
        principal: value.principal,
        name: value.name,
        role: from_candid_Role_n52(_uploadFile, _downloadFile, value.role),
        created_at: value.created_at,
        email: value.email
    };
}
function from_candid_record_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    total: bigint;
    items: Array<_ClientPublic>;
}): {
    total: bigint;
    items: Array<ClientPublic>;
} {
    return {
        total: value.total,
        items: from_candid_vec_n59(_uploadFile, _downloadFile, value.items)
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ClientId;
    status: _ClientStatus;
    company_name: string;
    created_at: _Timestamp;
    email: string;
    contact_name: string;
    phone: string;
}): {
    id: ClientId;
    status: ClientStatus;
    company_name: string;
    created_at: Timestamp;
    email: string;
    contact_name: string;
    phone: string;
} {
    return {
        id: value.id,
        status: from_candid_ClientStatus_n7(_uploadFile, _downloadFile, value.status),
        company_name: value.company_name,
        created_at: value.created_at,
        email: value.email,
        contact_name: value.contact_name,
        phone: value.phone
    };
}
function from_candid_record_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    total: bigint;
    items: Array<_JobPostingPublic>;
}): {
    total: bigint;
    items: Array<JobPostingPublic>;
} {
    return {
        total: value.total,
        items: from_candid_vec_n63(_uploadFile, _downloadFile, value.items)
    };
}
function from_candid_record_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    total: bigint;
    items: Array<_LeadPublic>;
}): {
    total: bigint;
    items: Array<LeadPublic>;
} {
    return {
        total: value.total,
        items: from_candid_vec_n67(_uploadFile, _downloadFile, value.items)
    };
}
function from_candid_record_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    total: bigint;
    items: Array<_ProjectPublic>;
}): {
    total: bigint;
    items: Array<ProjectPublic>;
} {
    return {
        total: value.total,
        items: from_candid_vec_n71(_uploadFile, _downloadFile, value.items)
    };
}
function from_candid_record_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    total: bigint;
    items: Array<_TaskPublic>;
}): {
    total: bigint;
    items: Array<TaskPublic>;
} {
    return {
        total: value.total,
        items: from_candid_vec_n75(_uploadFile, _downloadFile, value.items)
    };
}
function from_candid_record_n77(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    total: bigint;
    items: Array<_UserPublic>;
}): {
    total: bigint;
    items: Array<UserPublic>;
} {
    return {
        total: value.total,
        items: from_candid_vec_n78(_uploadFile, _downloadFile, value.items)
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Contract: null;
} | {
    PartTime: null;
} | {
    FullTime: null;
}): JobType {
    return "Contract" in value ? JobType.Contract : "PartTime" in value ? JobType.PartTime : "FullTime" in value ? JobType.FullTime : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    New: null;
} | {
    Closed: null;
} | {
    Contacted: null;
} | {
    Qualified: null;
}): LeadStatus {
    return "New" in value ? LeadStatus.New : "Closed" in value ? LeadStatus.Closed : "Contacted" in value ? LeadStatus.Contacted : "Qualified" in value ? LeadStatus.Qualified : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    OnHold: null;
} | {
    Planning: null;
} | {
    InProgress: null;
} | {
    Completed: null;
}): ProjectStatus {
    return "OnHold" in value ? ProjectStatus.OnHold : "Planning" in value ? ProjectStatus.Planning : "InProgress" in value ? ProjectStatus.InProgress : "Completed" in value ? ProjectStatus.Completed : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Done: null;
} | {
    ToDo: null;
} | {
    InProgress: null;
}): TaskStatus {
    return "Done" in value ? TaskStatus.Done : "ToDo" in value ? TaskStatus.ToDo : "InProgress" in value ? TaskStatus.InProgress : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Low: null;
} | {
    High: null;
} | {
    Medium: null;
}): TaskPriority {
    return "Low" in value ? TaskPriority.Low : "High" in value ? TaskPriority.High : "Medium" in value ? TaskPriority.Medium : value;
}
function from_candid_variant_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    member: null;
} | {
    admin: null;
}): Role {
    return "member" in value ? Role.member : "admin" in value ? Role.admin : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Inactive: null;
} | {
    Prospect: null;
} | {
    Active: null;
}): ClientStatus {
    return "Inactive" in value ? ClientStatus.Inactive : "Prospect" in value ? ClientStatus.Prospect : "Active" in value ? ClientStatus.Active : value;
}
function from_candid_vec_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ClientPublic>): Array<ClientPublic> {
    return value.map((x)=>from_candid_ClientPublic_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_JobPostingPublic>): Array<JobPostingPublic> {
    return value.map((x)=>from_candid_JobPostingPublic_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LeadPublic>): Array<LeadPublic> {
    return value.map((x)=>from_candid_LeadPublic_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ProjectPublic>): Array<ProjectPublic> {
    return value.map((x)=>from_candid_ProjectPublic_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TaskPublic>): Array<TaskPublic> {
    return value.map((x)=>from_candid_TaskPublic_n39(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n78(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserPublic>): Array<UserPublic> {
    return value.map((x)=>from_candid_UserPublic_n50(_uploadFile, _downloadFile, x));
}
function to_candid_ClientStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ClientStatus): _ClientStatus {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_CreateClientPayload_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateClientPayload): _CreateClientPayload {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_CreateJobPostingPayload_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateJobPostingPayload): _CreateJobPostingPayload {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_CreateLeadPayload_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateLeadPayload): _CreateLeadPayload {
    return to_candid_record_n18(_uploadFile, _downloadFile, value);
}
function to_candid_CreateProjectPayload_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateProjectPayload): _CreateProjectPayload {
    return to_candid_record_n26(_uploadFile, _downloadFile, value);
}
function to_candid_CreateTaskPayload_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateTaskPayload): _CreateTaskPayload {
    return to_candid_record_n34(_uploadFile, _downloadFile, value);
}
function to_candid_JobType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobType): _JobType {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_LeadStatus_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeadStatus): _LeadStatus {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_ProjectStatus_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectStatus): _ProjectStatus {
    return to_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function to_candid_Role_n79(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n80(_uploadFile, _downloadFile, value);
}
function to_candid_TaskPriority_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskPriority): _TaskPriority {
    return to_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function to_candid_TaskStatus_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskStatus): _TaskStatus {
    return to_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateClientPayload_n81(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateClientPayload): _UpdateClientPayload {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateJobPostingPayload_n82(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateJobPostingPayload): _UpdateJobPostingPayload {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateLeadPayload_n83(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateLeadPayload): _UpdateLeadPayload {
    return to_candid_record_n18(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateProjectPayload_n84(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateProjectPayload): _UpdateProjectPayload {
    return to_candid_record_n26(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateTaskPayload_n85(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateTaskPayload): _UpdateTaskPayload {
    return to_candid_record_n34(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ClientStatus | null): [] | [_ClientStatus] {
    return value === null ? candid_none() : candid_some(to_candid_ClientStatus_n3(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: boolean | null): [] | [boolean] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeadStatus | null): [] | [_LeadStatus] {
    return value === null ? candid_none() : candid_some(to_candid_LeadStatus_n19(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectStatus | null): [] | [_ProjectStatus] {
    return value === null ? candid_none() : candid_some(to_candid_ProjectStatus_n27(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskStatus | null): [] | [_TaskStatus] {
    return value === null ? candid_none() : candid_some(to_candid_TaskStatus_n35(_uploadFile, _downloadFile, value));
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    description: string;
    is_active: boolean;
    department: string;
    requirements: string;
    location: string;
    job_type: JobType;
}): {
    title: string;
    description: string;
    is_active: boolean;
    department: string;
    requirements: string;
    location: string;
    job_type: _JobType;
} {
    return {
        title: value.title,
        description: value.description,
        is_active: value.is_active,
        department: value.department,
        requirements: value.requirements,
        location: value.location,
        job_type: to_candid_JobType_n11(_uploadFile, _downloadFile, value.job_type)
    };
}
function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: LeadStatus;
    source: string;
    name: string;
    email: string;
    company: string;
    notes: string;
    phone: string;
}): {
    status: _LeadStatus;
    source: string;
    name: string;
    email: string;
    company: string;
    notes: string;
    phone: string;
} {
    return {
        status: to_candid_LeadStatus_n19(_uploadFile, _downloadFile, value.status),
        source: value.source,
        name: value.name,
        email: value.email,
        company: value.company,
        notes: value.notes,
        phone: value.phone
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: ClientStatus;
    company_name: string;
    email: string;
    contact_name: string;
    phone: string;
}): {
    status: _ClientStatus;
    company_name: string;
    email: string;
    contact_name: string;
    phone: string;
} {
    return {
        status: to_candid_ClientStatus_n3(_uploadFile, _downloadFile, value.status),
        company_name: value.company_name,
        email: value.email,
        contact_name: value.contact_name,
        phone: value.phone
    };
}
function to_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: ProjectStatus;
    name: string;
    description: string;
    end_date: string;
    start_date: string;
    progress: bigint;
    client_id: ClientId;
    budget: bigint;
    owner_principal: UserId;
}): {
    status: _ProjectStatus;
    name: string;
    description: string;
    end_date: string;
    start_date: string;
    progress: bigint;
    client_id: _ClientId;
    budget: bigint;
    owner_principal: _UserId;
} {
    return {
        status: to_candid_ProjectStatus_n27(_uploadFile, _downloadFile, value.status),
        name: value.name,
        description: value.description,
        end_date: value.end_date,
        start_date: value.start_date,
        progress: value.progress,
        client_id: value.client_id,
        budget: value.budget,
        owner_principal: value.owner_principal
    };
}
function to_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: TaskStatus;
    title: string;
    description: string;
    assigned_to: UserId;
    due_date: string;
    priority: TaskPriority;
    project_id: ProjectId;
}): {
    status: _TaskStatus;
    title: string;
    description: string;
    assigned_to: _UserId;
    due_date: string;
    priority: _TaskPriority;
    project_id: _ProjectId;
} {
    return {
        status: to_candid_TaskStatus_n35(_uploadFile, _downloadFile, value.status),
        title: value.title,
        description: value.description,
        assigned_to: value.assigned_to,
        due_date: value.due_date,
        priority: to_candid_TaskPriority_n37(_uploadFile, _downloadFile, value.priority),
        project_id: value.project_id
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobType): {
    Contract: null;
} | {
    PartTime: null;
} | {
    FullTime: null;
} {
    return value == JobType.Contract ? {
        Contract: null
    } : value == JobType.PartTime ? {
        PartTime: null
    } : value == JobType.FullTime ? {
        FullTime: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeadStatus): {
    New: null;
} | {
    Closed: null;
} | {
    Contacted: null;
} | {
    Qualified: null;
} {
    return value == LeadStatus.New ? {
        New: null
    } : value == LeadStatus.Closed ? {
        Closed: null
    } : value == LeadStatus.Contacted ? {
        Contacted: null
    } : value == LeadStatus.Qualified ? {
        Qualified: null
    } : value;
}
function to_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectStatus): {
    OnHold: null;
} | {
    Planning: null;
} | {
    InProgress: null;
} | {
    Completed: null;
} {
    return value == ProjectStatus.OnHold ? {
        OnHold: null
    } : value == ProjectStatus.Planning ? {
        Planning: null
    } : value == ProjectStatus.InProgress ? {
        InProgress: null
    } : value == ProjectStatus.Completed ? {
        Completed: null
    } : value;
}
function to_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskStatus): {
    Done: null;
} | {
    ToDo: null;
} | {
    InProgress: null;
} {
    return value == TaskStatus.Done ? {
        Done: null
    } : value == TaskStatus.ToDo ? {
        ToDo: null
    } : value == TaskStatus.InProgress ? {
        InProgress: null
    } : value;
}
function to_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskPriority): {
    Low: null;
} | {
    High: null;
} | {
    Medium: null;
} {
    return value == TaskPriority.Low ? {
        Low: null
    } : value == TaskPriority.High ? {
        High: null
    } : value == TaskPriority.Medium ? {
        Medium: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ClientStatus): {
    Inactive: null;
} | {
    Prospect: null;
} | {
    Active: null;
} {
    return value == ClientStatus.Inactive ? {
        Inactive: null
    } : value == ClientStatus.Prospect ? {
        Prospect: null
    } : value == ClientStatus.Active ? {
        Active: null
    } : value;
}
function to_candid_variant_n80(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    member: null;
} | {
    admin: null;
} {
    return value == Role.member ? {
        member: null
    } : value == Role.admin ? {
        admin: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
